---
- name: restart postgresql
  sudo: yes
  service: name=postgresql-{{de_db_pgsql_major}} state=restarted

- name: reload postgresql
  sudo: yes
  service: name=postgresql-{{de_db_pgsql_major}} state=reloaded
