---
- include: timezone.yaml
- include: iptables.yaml
- include: java7.yaml
- include: condor.yaml
- include: docker.yaml
- include: distribute-compose.yaml
- include: postgres.yaml
- include: db-creator.yaml
#- include: irods.yml
