---
# defaults file for elk-kibana
docker_repo_target_config_dir: /etc/iplant/de/docker-registry/certs/
docker_repo_storage_path:
docker:
  registry:
    # directory that will be the source of the public key on the ansible head node that will be copied to the
    # docker enabled ansible nodes
    cert_dir: /etc/iplant/de/docker_registry/source_cert/
    public_key: domain.crt
    private_key: domain.key